### ISSUE TITLE
Unable to get from dataset with a subdataset

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-remake#78]
Using the example from #69 ([comment](https://github.com/datalad/datalad-remake/issues/69#issuecomment-2520974110)) with untrusted execution removed, I still can not `datalad get` a file from the remake special remote. Similar problem was first observed in a "real" dataset by @m-wierzba.

This time the failure seems to be around installing the dataset itself. Here's some git-annex debug around the place where problems happen (traceback cut down):

```
(...)
[2024-12-18 16:57:17.465193413] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG Starting provision
[2024-12-18 16:57:17.465232607] (Remote.External) Starting provision
[INFO] Installing subdataset bar to glob input
[INFO] Attempting a clone into /tmp/tmpdlzv2ysg/bar
[INFO] Attempting to clone from file:///tmp/ds/bar to /tmp/tmpdlzv2ysg/bar
[2024-12-18 16:57:17.767716651] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> PROGRESS 0
[2024-12-18 16:57:17.767947867] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> PROGRESS 1
[INFO] Completed clone attempts for Dataset(/tmp/tmpdlzv2ysg/bar)
[2024-12-18 16:57:17.7742604] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG Traceback (most recent call last):
[2024-12-18 16:57:17.774406095] (Remote.External) Traceback (most recent call last):
[2024-12-18 16:57:17.774464916] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 889, in Listen
[2024-12-18 16:57:17.774525941] (Remote.External)   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 889, in Listen
[2024-12-18 16:57:17.774579692] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG     reply = self.protocol.command(line)
[2024-12-18 16:57:17.774771043] (Remote.External)     reply = self.protocol.command(line)
[2024-12-18 16:57:17.774824654] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-18 16:57:17.774894876] (Remote.External)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-18 16:57:17.77495023] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 564, in command
[2024-12-18 16:57:17.775049878] (Remote.External)   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 564, in command
[2024-12-18 16:57:17.775129558] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG     reply = method(parts[1])
[2024-12-18 16:57:17.775188329] (Remote.External)     reply = method(parts[1])
[2024-12-18 16:57:17.775244284] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG             ^^^^^^^^^^^^^^^^
[2024-12-18 16:57:17.775301652] (Remote.External)             ^^^^^^^^^^^^^^^^
[2024-12-18 16:57:17.775351236] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 613, in do_TRANSFER
[2024-12-18 16:57:17.775414996] (Remote.External)   File "/home/mszczepanik/.virtualenvs/rmk/lib/python3.11/site-packages/annexremote/annexremote.py", line 613, in do_TRANSFER
[2024-12-18 16:57:17.775467936] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG     func(key, file_)
[2024-12-18 16:57:17.775523741] (Remote.External)     func(key, file_)
[2024-12-18 16:57:17.775572112] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG   File "/home/mszczepanik/Documents/dl-rmk/datalad_remake/annexremotes/remake_remote.py", line 180, in transfer_retrieve
[2024-12-18 16:57:17.775633878] (Remote.External)   File "/home/mszczepanik/Documents/dl-rmk/datalad_remake/annexremotes/remake_remote.py", line 180, in transfer_retrieve
[2024-12-18 16:57:17.775685275] (Annex.ExternalAddonProcess) /home/mszczepanik/.virtualenvs/rmk/bin/git-annex-remote-datalad-remake[1] --> DEBUG     with provide_context(
[2024-12-18 16:57:17.775750899] (Remote.External)     with provide_context(
(...)
```

Not sure if that helps: I tried to trace the code path, which took me to `provision_cmd.py::install_subdataset`. It can be summed up as: `git submodule set-url` followed by `worktree.get(subdataset_path, get_data=False)` (where worktree is a Dataset object). It would seem that something - maybe this call, maybe some other - does not behave as expected when running within the special remote.

**Comment by christian-monch** [comment]
> ... 
> Not sure if that helps: I tried to trace the code path, which took me to `provision_cmd.py::install_subdataset`. It can be summed up as: `git submodule set-url` followed by `worktree.get(subdataset_path, get_data=False)` (where worktree is a Dataset object). It would seem that something - maybe this call, maybe some other - does not behave as expected when running within the special remote.

@mslw thank you very much for this investigation. I share your hypothesis. I verified that is it not due to the state of the provisioned worktree, because a "manual" execution of the mentioned commands in the provisioned worktree on the command line works.

**Comment by christian-monch** [comment]
The cause for the failure of `datalad provision` in an annex remote is that the environment variables `GIT_DIR` and `GIT_WORK_TREE` are set in the subprocesses of an annex remote.
